insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (1, 1, 'Flensburg – Schleswig', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (2, 2, 'Nordfriesland – Dithmarschen Nord', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (3, 3, 'Steinburg – Dithmarschen Süd', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (4, 4, 'Rendsburg-Eckernförde', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (5, 5, 'Kiel', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (6, 6, 'Plön – Neumünster', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (7, 7, 'Pinneberg', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (8, 8, 'Segeberg – Stormarn-Nord', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (9, 9, 'Ostholstein', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (10, 10, 'Herzogtum Lauenburg – Stormarn-Süd', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (11, 11, 'Lübeck', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (12, 12, 'Wismar – Nordwestmecklenburg – Parchim', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (13, 13, 'Schwerin – Ludwigslust', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (14, 14, 'Rostock', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (15, 15, 'Stralsund – Nordvorpommern – Rügen', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (16, 16, 'Greifswald – Demmin – Ostvorpommern', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (17, 17, 'Bad Doberan – Güstrow – Müritz', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (18, 18, 'Neubrandenburg – Mecklenburg-Strelitz – Uecker-Randow', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (19, 19, 'Hamburg-Mitte', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (20, 20, 'Hamburg-Altona', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (21, 21, 'Hamburg-Eimsbüttel', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (22, 22, 'Hamburg-Nord', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (23, 23, 'Hamburg-Wandsbek', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (24, 24, 'Hamburg-Bergedorf – Harburg', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (25, 25, 'Aurich – Emden', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (26, 26, 'Unterems', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (27, 27, 'Friesland – Wilhelmshaven', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (28, 28, 'Oldenburg – Ammerland', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (29, 29, 'Delmenhorst – Wesermarsch – Oldenburg-Land', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (30, 30, 'Cuxhaven – Stade II', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (31, 31, 'Stade I – Rotenburg II', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (32, 32, 'Mittelems', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (33, 33, 'Cloppenburg – Vechta', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (34, 34, 'Diepholz – Nienburg I', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (35, 35, 'Osterholz – Verden', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (36, 36, 'Rotenburg I – Soltau-Fallingbostel', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (37, 37, 'Harburg', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (38, 38, 'Lüchow-Dannenberg – Lüneburg', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (39, 39, 'Osnabrück-Land', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (40, 40, 'Stadt Osnabrück', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (41, 41, 'Nienburg II – Schaumburg', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (42, 42, 'Stadt Hannover I', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (43, 43, 'Stadt Hannover II', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (44, 44, 'Hannover-Land I', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (45, 45, 'Celle – Uelzen', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (46, 46, 'Gifhorn – Peine', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (47, 47, 'Hameln-Pyrmont – Holzminden', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (48, 48, 'Hannover-Land II', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (49, 49, 'Hildesheim', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (50, 50, 'Salzgitter – Wolfenbüttel', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (51, 51, 'Braunschweig', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (52, 52, 'Helmstedt – Wolfsburg', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (53, 53, 'Goslar – Northeim – Osterode', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (54, 54, 'Göttingen', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (55, 55, 'Bremen I', NULL, 11, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (56, 56, 'Bremen II – Bremerhaven', NULL, 11, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (57, 57, 'Prignitz – Ostprignitz-Ruppin – Havelland I', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (58, 58, 'Uckermark – Barnim I', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (59, 59, 'Oberhavel – Havelland II', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (60, 60, 'Märkisch-Oderland – Barnim II', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (61, 61, 'Brandenburg an der Havel – Potsdam-Mittelmark I – Havelland III – Teltow-Fläming I', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (62, 62, 'Potsdam – Potsdam-Mittelmark II – Teltow-Fläming II', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (63, 63, 'Dahme-Spreewald – Teltow-Fläming III – Oberspreewald-Lausitz I', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (64, 64, 'Frankfurt (Oder) – Oder-Spree', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (65, 65, 'Cottbus – Spree-Neiße', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (66, 66, 'Elbe-Elster – Oberspreewald-Lausitz II', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (67, 67, 'Altmark', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (68, 68, 'Börde – Jerichower Land', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (69, 69, 'Harz', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (70, 70, 'Magdeburg', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (71, 71, 'Dessau - Wittenberg', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (72, 72, 'Anhalt', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (73, 73, 'Halle', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (74, 74, 'Burgenland – Saalekreis', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (75, 75, 'Mansfeld', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (76, 76, 'Berlin-Mitte', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (77, 77, 'Berlin-Pankow', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (78, 78, 'Berlin-Reinickendorf', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (79, 79, 'Berlin-Spandau – Charlottenburg Nord', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (80, 80, 'Berlin-Steglitz – Zehlendorf', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (81, 81, 'Berlin-Charlottenburg – Wilmersdorf', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (82, 82, 'Berlin-Tempelhof – Schöneberg', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (83, 83, 'Berlin-Neukölln', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (84, 84, 'Berlin-Friedrichshain – Kreuzberg – Prenzlauer Berg Ost', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (85, 85, 'Berlin-Treptow – Köpenick', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (86, 86, 'Berlin-Marzahn – Hellersdorf', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (87, 87, 'Berlin-Lichtenberg', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (88, 88, 'Aachen', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (89, 89, 'Kreis Aachen', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (90, 90, 'Heinsberg', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (91, 91, 'Düren', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (92, 92, 'Erftkreis I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (93, 93, 'Euskirchen – Erftkreis II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (94, 94, 'Köln I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (95, 95, 'Köln II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (96, 96, 'Köln III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (97, 97, 'Bonn', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (98, 98, 'Rhein-Sieg-Kreis I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (99, 99, 'Rhein-Sieg-Kreis II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (100, 100, 'Oberbergischer Kreis', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (101, 101, 'Rheinisch-Bergischer Kreis', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (102, 102, 'Leverkusen – Köln IV', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (103, 103, 'Wuppertal I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (104, 104, 'Solingen – Remscheid – Wuppertal II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (105, 105, 'Mettmann I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (106, 106, 'Mettmann II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (107, 107, 'Düsseldorf I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (108, 108, 'Düsseldorf II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (109, 109, 'Neuss I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (110, 110, 'Mönchengladbach', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (111, 111, 'Krefeld I – Neuss II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (112, 112, 'Viersen', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (113, 113, 'Kleve', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (114, 114, 'Wesel I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (115, 115, 'Krefeld II – Wesel II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (116, 116, 'Duisburg I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (117, 117, 'Duisburg II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (118, 118, 'Oberhausen – Wesel III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (119, 119, 'Mülheim – Essen I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (120, 120, 'Essen II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (121, 121, 'Essen III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (122, 122, 'Recklinghausen I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (123, 123, 'Recklinghausen II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (124, 124, 'Gelsenkirchen', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (125, 125, 'Steinfurt I – Borken I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (126, 126, 'Bottrop – Recklinghausen III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (127, 127, 'Borken II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (128, 128, 'Coesfeld – Steinfurt II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (129, 129, 'Steinfurt III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (130, 130, 'Münster', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (131, 131, 'Warendorf', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (132, 132, 'Gütersloh', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (133, 133, 'Bielefeld', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (134, 134, 'Herford – Minden-Lübbecke II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (135, 135, 'Minden-Lübbecke I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (136, 136, 'Lippe I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (137, 137, 'Höxter – Lippe II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (138, 138, 'Paderborn', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (139, 139, 'Hagen – Ennepe-Ruhr-Kreis I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (140, 140, 'Ennepe-Ruhr-Kreis II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (141, 141, 'Bochum I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (142, 142, 'Herne – Bochum II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (143, 143, 'Dortmund I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (144, 144, 'Dortmund II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (145, 145, 'Unna I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (146, 146, 'Hamm – Unna II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (147, 147, 'Soest', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (148, 148, 'Hochsauerlandkreis', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (149, 149, 'Siegen-Wittgenstein', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (150, 150, 'Olpe – Märkischer Kreis I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (151, 151, 'Märkischer Kreis II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (152, 152, 'Nordsachsen', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (153, 153, 'Leipzig I', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (154, 154, 'Leipzig II', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (155, 155, 'Leipzig-Land', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (156, 156, 'Meißen', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (157, 157, 'Bautzen I', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (158, 158, 'Görlitz', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (159, 159, 'Sächsische Schweiz – Osterzgebirge', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (160, 160, 'Dresden I', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (161, 161, 'Dresden II – Bautzen II', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (162, 162, 'Mittelsachsen', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (163, 163, 'Chemnitz', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (164, 164, 'Chemnitzer Umland – Erzgebirgskreis II', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (165, 165, 'Erzgebirgskreis I', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (166, 166, 'Zwickau', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (167, 167, 'Vogtlandkreis', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (168, 168, 'Waldeck', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (169, 169, 'Kassel', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (170, 170, 'Werra-Meißner – Hersfeld-Rotenburg', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (171, 171, 'Schwalm-Eder', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (172, 172, 'Marburg', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (173, 173, 'Lahn-Dill', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (174, 174, 'Gießen', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (175, 175, 'Fulda', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (176, 176, 'Hochtaunus', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (177, 177, 'Wetterau', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (178, 178, 'Rheingau-Taunus – Limburg', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (179, 179, 'Wiesbaden', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (180, 180, 'Hanau', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (181, 181, 'Main-Taunus', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (182, 182, 'Frankfurt am Main I', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (183, 183, 'Frankfurt am Main II', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (184, 184, 'Groß-Gerau', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (185, 185, 'Offenbach', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (186, 186, 'Darmstadt', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (187, 187, 'Odenwald', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (188, 188, 'Bergstraße', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (189, 189, 'Eichsfeld – Nordhausen – Unstrut-Hainich-Kreis I', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (190, 190, 'Eisenach – Wartburgkreis – Unstrut-Hainich-Kreis II', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (191, 191, 'Kyffhäuserkreis – Sömmerda – Weimarer Land I', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (192, 192, 'Gotha – Ilm-Kreis', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (193, 193, 'Erfurt – Weimar – Weimarer Land II', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (194, 194, 'Gera – Jena – Saale-Holzland-Kreis', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (195, 195, 'Greiz – Altenburger Land', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (196, 196, 'Sonneberg – Saalfeld-Rudolstadt – Saale-Orla-Kreis', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (197, 197, 'Suhl – Schmalkalden-Meiningen – Hildburghausen', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (198, 198, 'Neuwied', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (199, 199, 'Ahrweiler', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (200, 200, 'Koblenz', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (201, 201, 'Mosel/Rhein-Hunsrück', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (202, 202, 'Kreuznach', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (203, 203, 'Bitburg', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (204, 204, 'Trier', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (205, 205, 'Montabaur', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (206, 206, 'Mainz', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (207, 207, 'Worms', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (208, 208, 'Ludwigshafen/Frankenthal', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (209, 209, 'Neustadt – Speyer', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (210, 210, 'Kaiserslautern', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (211, 211, 'Pirmasens', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (212, 212, 'Südpfalz', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (213, 213, 'Altötting', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (214, 214, 'Erding – Ebersberg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (215, 215, 'Freising', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (216, 216, 'Fürstenfeldbruck', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (217, 217, 'Ingolstadt', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (218, 218, 'München-Nord', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (219, 219, 'München-Ost', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (220, 220, 'München-Süd', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (221, 221, 'München-West/Mitte', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (222, 222, 'München-Land', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (223, 223, 'Rosenheim', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (224, 224, 'Starnberg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (225, 225, 'Traunstein', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (226, 226, 'Weilheim', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (227, 227, 'Deggendorf', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (228, 228, 'Landshut', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (229, 229, 'Passau', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (230, 230, 'Rottal-Inn', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (231, 231, 'Straubing', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (232, 232, 'Amberg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (233, 233, 'Regensburg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (234, 234, 'Schwandorf', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (235, 235, 'Weiden', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (236, 236, 'Bamberg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (237, 237, 'Bayreuth', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (238, 238, 'Coburg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (239, 239, 'Hof', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (240, 240, 'Kulmbach', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (241, 241, 'Ansbach', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (242, 242, 'Erlangen', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (243, 243, 'Fürth', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (244, 244, 'Nürnberg-Nord', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (245, 245, 'Nürnberg-Süd', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (246, 246, 'Roth', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (247, 247, 'Aschaffenburg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (248, 248, 'Bad Kissingen', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (249, 249, 'Main-Spessart', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (250, 250, 'Schweinfurt', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (251, 251, 'Würzburg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (252, 252, 'Augsburg-Stadt', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (253, 253, 'Augsburg-Land', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (254, 254, 'Donau-Ries', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (255, 255, 'Neu-Ulm', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (256, 256, 'Oberallgäu', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (257, 257, 'Ostallgäu', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (258, 258, 'Stuttgart I', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (259, 259, 'Stuttgart II', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (260, 260, 'Böblingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (261, 261, 'Esslingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (262, 262, 'Nürtingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (263, 263, 'Göppingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (264, 264, 'Waiblingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (265, 265, 'Ludwigsburg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (266, 266, 'Neckar-Zaber', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (267, 267, 'Heilbronn', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (268, 268, 'Schwäbisch Hall – Hohenlohe', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (269, 269, 'Backnang – Schwäbisch Gmünd', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (270, 270, 'Aalen – Heidenheim', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (271, 271, 'Karlsruhe-Stadt', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (272, 272, 'Karlsruhe-Land', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (273, 273, 'Rastatt', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (274, 274, 'Heidelberg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (275, 275, 'Mannheim', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (276, 276, 'Odenwald – Tauber', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (277, 277, 'Rhein-Neckar', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (278, 278, 'Bruchsal – Schwetzingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (279, 279, 'Pforzheim', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (280, 280, 'Calw', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (281, 281, 'Freiburg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (282, 282, 'Lörrach – Müllheim', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (283, 283, 'Emmendingen – Lahr', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (284, 284, 'Offenburg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (285, 285, 'Rottweil – Tuttlingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (286, 286, 'Schwarzwald-Baar', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (287, 287, 'Konstanz', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (288, 288, 'Waldshut', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (289, 289, 'Reutlingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (290, 290, 'Tübingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (291, 291, 'Ulm', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (292, 292, 'Biberach', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (293, 293, 'Bodensee', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (294, 294, 'Ravensburg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (295, 295, 'Zollernalb – Sigmaringen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (296, 296, 'Saarbrücken', NULL, 12, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (297, 297, 'Saarlouis', NULL, 12, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (298, 298, 'St. Wendel', NULL, 12, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (299, 299, 'Homburg', NULL, 12, 2009);
