insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (300, 1, 'Flensburg – Schleswig', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (301, 2, 'Nordfriesland – Dithmarschen Nord', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (302, 3, 'Steinburg – Dithmarschen Süd', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (303, 4, 'Rendsburg-Eckernförde', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (304, 5, 'Kiel', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (305, 6, 'Plön – Neumünster', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (306, 7, 'Pinneberg', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (307, 8, 'Segeberg – Stormarn-Mitte', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (308, 9, 'Ostholstein – Stormarn-Nord', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (309, 10, 'Herzogtum Lauenburg – Stormarn-Süd', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (310, 11, 'Lübeck', NULL, 13);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (311, 12, 'Schwerin – Ludwigslust-Parchim I – Nordwestmecklenburg I', NULL, 15);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (312, 13, 'Ludwigslust-Parchim II – Nordwestmecklenburg II – Landkreis Rostock I', NULL, 15);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (313, 14, 'Rostock – Landkreis Rostock II', NULL, 15);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (314, 15, 'Vorpommern-Rügen – Vorpommern-Greifswald I', NULL, 15);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (315, 16, 'Mecklenburgische Seenplatte I – Vorpommern-Greifswald II ', NULL, 15);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (316, 17, 'Mecklenburgische Seenplatte II – Landkreis Rostock III', NULL, 15);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (317, 18, 'Hamburg-Mitte', NULL, 8);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (318, 19, 'Hamburg-Altona', NULL, 8);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (319, 20, 'Hamburg-Eimsbüttel', NULL, 8);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (320, 21, 'Hamburg-Nord', NULL, 8);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (321, 22, 'Hamburg-Wandsbek', NULL, 8);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (322, 23, 'Hamburg-Bergedorf – Harburg', NULL, 8);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (323, 24, 'Aurich – Emden', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (324, 25, 'Unterems', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (325, 26, 'Friesland – Wilhelmshaven – Wittmund', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (326, 27, 'Oldenburg – Ammerland', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (327, 28, 'Delmenhorst – Wesermarsch – Oldenburg-Land', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (328, 29, 'Cuxhaven – Stade II', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (329, 30, 'Stade I – Rotenburg II', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (330, 31, 'Mittelems', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (331, 32, 'Cloppenburg – Vechta', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (332, 33, 'Diepholz – Nienburg I', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (333, 34, 'Osterholz – Verden', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (334, 35, 'Rotenburg I – Heidekreis', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (335, 36, 'Harburg', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (336, 37, 'Lüchow-Dannenberg – Lüneburg', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (337, 38, 'Osnabrück-Land', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (338, 39, 'Stadt Osnabrück', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (339, 40, 'Nienburg II – Schaumburg', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (340, 41, 'Stadt Hannover I', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (341, 42, 'Stadt Hannover II', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (342, 43, 'Hannover-Land I', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (343, 44, 'Celle – Uelzen', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (344, 45, 'Gifhorn – Peine', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (345, 46, 'Hameln-Pyrmont – Holzminden', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (346, 47, 'Hannover-Land II', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (347, 48, 'Hildesheim', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (348, 49, 'Salzgitter – Wolfenbüttel', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (349, 50, 'Braunschweig', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (350, 51, 'Helmstedt – Wolfsburg', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (351, 52, 'Goslar – Northeim – Osterode', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (352, 53, 'Göttingen', NULL, 3);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (353, 54, 'Bremen I', NULL, 11);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (354, 55, 'Bremen II – Bremerhaven', NULL, 11);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (355, 56, 'Prignitz – Ostprignitz-Ruppin – Havelland I', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (356, 57, 'Uckermark – Barnim I', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (357, 58, 'Oberhavel – Havelland II', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (358, 59, 'Märkisch-Oderland – Barnim II', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (359, 60, 'Brandenburg an der Havel – Potsdam-Mittelmark I – Havelland III – Teltow-Fläming I', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (360, 61, 'Potsdam – Potsdam-Mittelmark II – Teltow-Fläming II', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (361, 62, 'Dahme-Spreewald – Teltow-Fläming III – Oberspreewald-Lausitz I', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (362, 63, 'Frankfurt (Oder) – Oder-Spree', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (363, 64, 'Cottbus – Spree-Neiße', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (364, 65, 'Elbe-Elster – Oberspreewald-Lausitz II', NULL, 14);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (365, 66, 'Altmark', NULL, 6);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (366, 67, 'Börde – Jerichower Land', NULL, 6);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (367, 68, 'Harz', NULL, 6);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (368, 69, 'Magdeburg', NULL, 6);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (369, 70, 'Dessau – Wittenberg', NULL, 6);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (370, 71, 'Anhalt', NULL, 6);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (371, 72, 'Halle', NULL, 6);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (372, 73, 'Burgenland – Saalekreis', NULL, 6);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (373, 74, 'Mansfeld', NULL, 6);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (374, 75, 'Berlin-Mitte', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (375, 76, 'Berlin-Pankow', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (376, 77, 'Berlin-Reinickendorf', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (377, 78, 'Berlin-Spandau – Charlottenburg Nord', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (378, 79, 'Berlin-Steglitz-Zehlendorf', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (379, 80, 'Berlin-Charlottenburg-Wilmersdorf', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (380, 81, 'Berlin-Tempelhof-Schöneberg', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (381, 82, 'Berlin-Neukölln', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (382, 83, 'Berlin-Friedrichshain-Kreuzberg – Prenzlauer Berg Ost', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (383, 84, 'Berlin-Treptow-Köpenick', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (384, 85, 'Berlin-Marzahn-Hellersdorf', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (385, 86, 'Berlin-Lichtenberg', NULL, 1);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (386, 87, 'Aachen I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (387, 88, 'Aachen II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (388, 89, 'Heinsberg', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (389, 90, 'Düren', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (390, 91, 'Rhein-Erft-Kreis I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (391, 92, 'Euskirchen – Rhein-Erft-Kreis II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (392, 93, 'Köln I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (393, 94, 'Köln II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (394, 95, 'Köln III', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (395, 96, 'Bonn', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (396, 97, 'Rhein-Sieg-Kreis I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (397, 98, 'Rhein-Sieg-Kreis II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (398, 99, 'Oberbergischer Kreis', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (399, 100, 'Rheinisch-Bergischer Kreis', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (400, 101, 'Leverkusen – Köln IV', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (401, 102, 'Wuppertal I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (402, 103, 'Solingen – Remscheid – Wuppertal II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (403, 104, 'Mettmann I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (404, 105, 'Mettmann II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (405, 106, 'Düsseldorf I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (406, 107, 'Düsseldorf II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (407, 108, 'Neuss I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (408, 109, 'Mönchengladbach', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (409, 110, 'Krefeld I – Neuss II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (410, 111, 'Viersen', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (411, 112, 'Kleve', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (412, 113, 'Wesel I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (413, 114, 'Krefeld II – Wesel II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (414, 115, 'Duisburg I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (415, 116, 'Duisburg II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (416, 117, 'Oberhausen – Wesel III', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (417, 118, 'Mülheim – Essen I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (418, 119, 'Essen II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (419, 120, 'Essen III', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (420, 121, 'Recklinghausen I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (421, 122, 'Recklinghausen II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (422, 123, 'Gelsenkirchen', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (423, 124, 'Steinfurt I – Borken I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (424, 125, 'Bottrop – Recklinghausen III', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (425, 126, 'Borken II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (426, 127, 'Coesfeld – Steinfurt II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (427, 128, 'Steinfurt III', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (428, 129, 'Münster', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (429, 130, 'Warendorf', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (430, 131, 'Gütersloh I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (431, 132, 'Bielefeld – Gütersloh II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (432, 133, 'Herford – Minden-Lübbecke II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (433, 134, 'Minden-Lübbecke I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (434, 135, 'Lippe I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (435, 136, 'Höxter – Lippe II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (436, 137, 'Paderborn – Gütersloh III', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (437, 138, 'Hagen – Ennepe-Ruhr-Kreis I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (438, 139, 'Ennepe-Ruhr-Kreis II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (439, 140, 'Bochum I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (440, 141, 'Herne – Bochum II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (441, 142, 'Dortmund I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (442, 143, 'Dortmund II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (443, 144, 'Unna I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (444, 145, 'Hamm – Unna II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (445, 146, 'Soest', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (446, 147, 'Hochsauerlandkreis', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (447, 148, 'Siegen-Wittgenstein', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (448, 149, 'Olpe – Märkischer Kreis I', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (449, 150, 'Märkischer Kreis II', NULL, 5);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (450, 151, 'Nordsachsen', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (451, 152, 'Leipzig I', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (452, 153, 'Leipzig II', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (453, 154, 'Leipzig-Land', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (454, 155, 'Meißen', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (455, 156, 'Bautzen I', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (456, 157, 'Görlitz', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (457, 158, 'Sächsische Schweiz-Osterzgebirge', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (458, 159, 'Dresden I', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (459, 160, 'Dresden II – Bautzen II', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (460, 161, 'Mittelsachsen', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (461, 162, 'Chemnitz', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (462, 163, 'Chemnitzer Umland – Erzgebirgskreis II', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (463, 164, 'Erzgebirgskreis I', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (464, 165, 'Zwickau', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (465, 166, 'Vogtlandkreis', NULL, 16);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (466, 167, 'Waldeck', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (467, 168, 'Kassel', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (468, 169, 'Werra-Meißner – Hersfeld-Rotenburg', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (469, 170, 'Schwalm-Eder', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (470, 171, 'Marburg', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (471, 172, 'Lahn-Dill', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (472, 173, 'Gießen', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (473, 174, 'Fulda', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (474, 175, 'Main-Kinzig – Wetterau II – Schotten', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (475, 176, 'Hochtaunus', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (476, 177, 'Wetterau I', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (477, 178, 'Rheingau-Taunus – Limburg', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (478, 179, 'Wiesbaden', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (479, 180, 'Hanau', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (480, 181, 'Main-Taunus', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (481, 182, 'Frankfurt am Main I', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (482, 183, 'Frankfurt am Main II', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (483, 184, 'Groß-Gerau', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (484, 185, 'Offenbach', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (485, 186, 'Darmstadt', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (486, 187, 'Odenwald', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (487, 188, 'Bergstraße', NULL, 7);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (488, 189, 'Eichsfeld – Nordhausen – Unstrut-Hainich-Kreis I', NULL, 9);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (489, 190, 'Eisenach – Wartburgkreis – Unstrut-Hainich-Kreis II', NULL, 9);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (490, 191, 'Kyffhäuserkreis – Sömmerda – Weimarer Land I', NULL, 9);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (491, 192, 'Gotha – Ilm-Kreis', NULL, 9);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (492, 193, 'Erfurt – Weimar – Weimarer Land II', NULL, 9);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (493, 194, 'Gera – Jena – Saale-Holzland-Kreis', NULL, 9);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (494, 195, 'Greiz – Altenburger Land', NULL, 9);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (495, 196, 'Sonneberg – Saalfeld-Rudolstadt – Saale-Orla-Kreis', NULL, 9);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (496, 197, 'Suhl – Schmalkalden-Meiningen – Hildburghausen', NULL, 9);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (497, 198, 'Neuwied', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (498, 199, 'Ahrweiler', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (499, 200, 'Koblenz', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (500, 201, 'Mosel/Rhein-Hunsrück', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (501, 202, 'Kreuznach', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (502, 203, 'Bitburg', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (503, 204, 'Trier', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (504, 205, 'Montabaur', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (505, 206, 'Mainz', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (506, 207, 'Worms', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (507, 208, 'Ludwigshafen/Frankenthal', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (508, 209, 'Neustadt – Speyer', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (509, 210, 'Kaiserslautern', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (510, 211, 'Pirmasens', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (511, 212, 'Südpfalz', NULL, 2);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (512, 213, 'Altötting', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (513, 214, 'Erding – Ebersberg', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (514, 215, 'Freising', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (515, 216, 'Fürstenfeldbruck', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (516, 217, 'Ingolstadt', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (517, 218, 'München-Nord', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (518, 219, 'München-Ost', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (519, 220, 'München-Süd', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (520, 221, 'München-West/Mitte', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (521, 222, 'München-Land', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (522, 223, 'Rosenheim', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (523, 224, 'Starnberg', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (524, 225, 'Traunstein', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (525, 226, 'Weilheim', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (526, 227, 'Deggendorf', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (527, 228, 'Landshut', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (528, 229, 'Passau', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (529, 230, 'Rottal-Inn', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (530, 231, 'Straubing', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (531, 232, 'Amberg', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (532, 233, 'Regensburg', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (533, 234, 'Schwandorf', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (534, 235, 'Weiden', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (535, 236, 'Bamberg', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (536, 237, 'Bayreuth', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (537, 238, 'Coburg', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (538, 239, 'Hof', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (539, 240, 'Kulmbach', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (540, 241, 'Ansbach', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (541, 242, 'Erlangen', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (542, 243, 'Fürth', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (543, 244, 'Nürnberg-Nord', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (544, 245, 'Nürnberg-Süd', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (545, 246, 'Roth', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (546, 247, 'Aschaffenburg', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (547, 248, 'Bad Kissingen', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (548, 249, 'Main-Spessart', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (549, 250, 'Schweinfurt', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (550, 251, 'Würzburg', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (551, 252, 'Augsburg-Stadt', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (552, 253, 'Augsburg-Land', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (553, 254, 'Donau-Ries', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (554, 255, 'Neu-Ulm', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (555, 256, 'Oberallgäu', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (556, 257, 'Ostallgäu', NULL, 4);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (557, 258, 'Stuttgart I', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (558, 259, 'Stuttgart II', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (559, 260, 'Böblingen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (560, 261, 'Esslingen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (561, 262, 'Nürtingen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (562, 263, 'Göppingen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (563, 264, 'Waiblingen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (564, 265, 'Ludwigsburg', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (565, 266, 'Neckar-Zaber', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (566, 267, 'Heilbronn', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (567, 268, 'Schwäbisch Hall – Hohenlohe', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (568, 269, 'Backnang – Schwäbisch Gmünd', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (569, 270, 'Aalen – Heidenheim', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (570, 271, 'Karlsruhe-Stadt', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (571, 272, 'Karlsruhe-Land', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (572, 273, 'Rastatt', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (573, 274, 'Heidelberg', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (574, 275, 'Mannheim', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (575, 276, 'Odenwald – Tauber', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (576, 277, 'Rhein-Neckar', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (577, 278, 'Bruchsal – Schwetzingen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (578, 279, 'Pforzheim', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (579, 280, 'Calw', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (580, 281, 'Freiburg', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (581, 282, 'Lörrach – Müllheim', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (582, 283, 'Emmendingen – Lahr', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (583, 284, 'Offenburg', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (584, 285, 'Rottweil – Tuttlingen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (585, 286, 'Schwarzwald-Baar', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (586, 287, 'Konstanz', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (587, 288, 'Waldshut', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (588, 289, 'Reutlingen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (589, 290, 'Tübingen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (590, 291, 'Ulm', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (591, 292, 'Biberach', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (592, 293, 'Bodensee', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (593, 294, 'Ravensburg', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (594, 295, 'Zollernalb – Sigmaringen', NULL, 10);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (595, 296, 'Saarbrücken', NULL, 12);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (596, 297, 'Saarlouis', NULL, 12);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (597, 298, 'St. Wendel', NULL, 12);
insert into Wahlkreis (wkid, wknr, name, outline, fsid) VALUES (598, 299, 'Homburg', NULL, 12);
