-- works
insert into Party (pid, name, shorthand, website, colourcode) VALUES (1, 'NPD', 'X1','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (2, 'SPD', 'X2','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (3, 'DIE LINKE', 'X3','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (4, 'FDP', 'X4','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (5, 'GRÜNE', 'X5','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (6, 'VIOLETTEN', 'X6','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (7, 'PIRATEN', 'X7','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (8, 'ödp', 'X8','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (9, 'CSU', 'X9','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (10, 'BüSo', 'X10','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (11, 'DVU', 'X11','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (12, 'CDU', 'X12','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (13, 'MLPD', 'X13','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (14, 'RRP', 'X14','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (15, 'BP', 'X15','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (16, 'Tierschutz', 'X16','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (17, 'PBC', 'X17','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (18, 'RENTNER', 'X18','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (19, 'REP', 'X19','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (20, 'Volksabst.', 'X20','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (21, 'DKP', 'X21','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (22, 'FAMILIE', 'X22','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (23, 'ADM', 'X23','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (24, 'Freie Union', 'X24','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (25, 'FWD', 'X25','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (26, 'PSG', 'X26','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (27, 'CM', 'X27','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (28, 'ZENTRUM', 'X28','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (29, 'DIE VIOLETTEN', 'X29','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (30, 'Die Tierschutzpartei', 'X30','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (31, 'Die PARTEI', 'X31','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (32, 'FREIE WÄHLER', 'X32','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (33, 'AfD', 'X33','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (34, 'BIG', 'X34','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (35, 'VERNUNFT', 'X35','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (36, 'ÖDP', 'X36','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (37, 'pro Deutschland', 'X37','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (38, 'NEIN!', 'X38','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (39, 'Volksabstimmung', 'X39','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (40, 'DIE FRAUEN', 'X40','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (41, 'Bündnis21/RRP', 'X41','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (42, 'Tierschutzpartei', 'X42','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (43, 'DIE RECHTE', 'X43','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (44, 'Nichtwähler', 'X44','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (45, 'BGD', 'X45','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (46, 'B', 'X46','X','X');
