insert into Party (pid, name, shorthand, website, colourcode) VALUES (1, 'NPD', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (2, 'SPD', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (3, 'DIE LINKE', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (4, 'FDP', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (5, 'GRÜNE', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (6, 'VIOLETTEN', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (7, 'PIRATEN', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (8, 'ödp', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (9, 'CSU', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (10, 'BüSo', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (11, 'DVU', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (12, 'CDU', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (13, 'MLPD', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (14, 'RRP', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (15, 'BP', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (16, 'Tierschutz', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (17, 'PBC', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (18, 'RENTNER', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (19, 'REP', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (20, 'Volksabst.', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (21, 'DKP', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (22, 'FAMILIE', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (23, 'ADM', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (24, 'Freie Union', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (25, 'FWD', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (26, 'PSG', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (27, 'CM', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (28, 'ZENTRUM', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (29, 'DIE VIOLETTEN', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (30, 'Die Tierschutzpartei', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (31, 'Die PARTEI', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (32, 'FREIE WÄHLER', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (33, 'AfD', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (34, 'BIG', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (35, 'VERNUNFT', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (36, 'ÖDP', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (37, 'pro Deutschland', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (38, 'NEIN!', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (39, 'Volksabstimmung', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (40, 'DIE FRAUEN', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (41, 'Bündnis21/RRP', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (42, 'Tierschutzpartei', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (43, 'DIE RECHTE', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (44, 'Nichtwähler', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (45, 'BGD', 'X','X','X');
insert into Party (pid, name, shorthand, website, colourcode) VALUES (46, 'B', 'X','X','X');
