insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (1, 1, 'Flensburg – Schleswig', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (2, 1, 'Flensburg – Schleswig', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (3, 2, 'Nordfriesland – Dithmarschen Nord', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (4, 2, 'Nordfriesland – Dithmarschen Nord', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (5, 3, 'Steinburg – Dithmarschen Süd', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (6, 3, 'Steinburg – Dithmarschen Süd', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (7, 4, 'Rendsburg-Eckernförde', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (8, 4, 'Rendsburg-Eckernförde', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (9, 5, 'Kiel', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (10, 5, 'Kiel', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (11, 6, 'Plön – Neumünster', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (12, 6, 'Plön – Neumünster', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (13, 7, 'Pinneberg', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (14, 7, 'Pinneberg', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (15, 8, 'Segeberg – Stormarn-Mitte', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (16, 8, 'Segeberg – Stormarn-Mitte', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (17, 9, 'Ostholstein – Stormarn-Nord', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (18, 9, 'Ostholstein – Stormarn-Nord', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (19, 10, 'Herzogtum Lauenburg – Stormarn-Süd', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (20, 10, 'Herzogtum Lauenburg – Stormarn-Süd', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (21, 11, 'Lübeck', NULL, 13, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (22, 11, 'Lübeck', NULL, 13, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (23, 12, 'Schwerin – Ludwigslust-Parchim I – Nordwestmecklenburg I', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (24, 12, 'Schwerin – Ludwigslust-Parchim I – Nordwestmecklenburg I', NULL, 15, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (25, 13, 'Ludwigslust-Parchim II – Nordwestmecklenburg II – Landkreis Rostock I', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (26, 13, 'Ludwigslust-Parchim II – Nordwestmecklenburg II – Landkreis Rostock I', NULL, 15, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (27, 14, 'Rostock – Landkreis Rostock II', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (28, 14, 'Rostock – Landkreis Rostock II', NULL, 15, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (29, 15, 'Vorpommern-Rügen – Vorpommern-Greifswald I', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (30, 15, 'Vorpommern-Rügen – Vorpommern-Greifswald I', NULL, 15, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (31, 16, 'Mecklenburgische Seenplatte I – Vorpommern-Greifswald II ', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (32, 16, 'Mecklenburgische Seenplatte I – Vorpommern-Greifswald II ', NULL, 15, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (33, 17, 'Mecklenburgische Seenplatte II – Landkreis Rostock III', NULL, 15, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (34, 17, 'Mecklenburgische Seenplatte II – Landkreis Rostock III', NULL, 15, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (35, 18, 'Hamburg-Mitte', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (36, 18, 'Hamburg-Mitte', NULL, 8, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (37, 19, 'Hamburg-Altona', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (38, 19, 'Hamburg-Altona', NULL, 8, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (39, 20, 'Hamburg-Eimsbüttel', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (40, 20, 'Hamburg-Eimsbüttel', NULL, 8, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (41, 21, 'Hamburg-Nord', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (42, 21, 'Hamburg-Nord', NULL, 8, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (43, 22, 'Hamburg-Wandsbek', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (44, 22, 'Hamburg-Wandsbek', NULL, 8, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (45, 23, 'Hamburg-Bergedorf – Harburg', NULL, 8, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (46, 23, 'Hamburg-Bergedorf – Harburg', NULL, 8, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (47, 24, 'Aurich – Emden', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (48, 24, 'Aurich – Emden', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (49, 25, 'Unterems', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (50, 25, 'Unterems', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (51, 26, 'Friesland – Wilhelmshaven – Wittmund', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (52, 26, 'Friesland – Wilhelmshaven – Wittmund', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (53, 27, 'Oldenburg – Ammerland', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (54, 27, 'Oldenburg – Ammerland', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (55, 28, 'Delmenhorst – Wesermarsch – Oldenburg-Land', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (56, 28, 'Delmenhorst – Wesermarsch – Oldenburg-Land', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (57, 29, 'Cuxhaven – Stade II', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (58, 29, 'Cuxhaven – Stade II', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (59, 30, 'Stade I – Rotenburg II', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (60, 30, 'Stade I – Rotenburg II', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (61, 31, 'Mittelems', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (62, 31, 'Mittelems', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (63, 32, 'Cloppenburg – Vechta', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (64, 32, 'Cloppenburg – Vechta', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (65, 33, 'Diepholz – Nienburg I', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (66, 33, 'Diepholz – Nienburg I', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (67, 34, 'Osterholz – Verden', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (68, 34, 'Osterholz – Verden', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (69, 35, 'Rotenburg I – Heidekreis', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (70, 35, 'Rotenburg I – Heidekreis', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (71, 36, 'Harburg', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (72, 36, 'Harburg', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (73, 37, 'Lüchow-Dannenberg – Lüneburg', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (74, 37, 'Lüchow-Dannenberg – Lüneburg', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (75, 38, 'Osnabrück-Land', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (76, 38, 'Osnabrück-Land', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (77, 39, 'Stadt Osnabrück', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (78, 39, 'Stadt Osnabrück', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (79, 40, 'Nienburg II – Schaumburg', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (80, 40, 'Nienburg II – Schaumburg', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (81, 41, 'Stadt Hannover I', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (82, 41, 'Stadt Hannover I', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (83, 42, 'Stadt Hannover II', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (84, 42, 'Stadt Hannover II', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (85, 43, 'Hannover-Land I', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (86, 43, 'Hannover-Land I', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (87, 44, 'Celle – Uelzen', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (88, 44, 'Celle – Uelzen', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (89, 45, 'Gifhorn – Peine', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (90, 45, 'Gifhorn – Peine', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (91, 46, 'Hameln-Pyrmont – Holzminden', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (92, 46, 'Hameln-Pyrmont – Holzminden', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (93, 47, 'Hannover-Land II', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (94, 47, 'Hannover-Land II', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (95, 48, 'Hildesheim', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (96, 48, 'Hildesheim', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (97, 49, 'Salzgitter – Wolfenbüttel', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (98, 49, 'Salzgitter – Wolfenbüttel', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (99, 50, 'Braunschweig', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (100, 50, 'Braunschweig', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (101, 51, 'Helmstedt – Wolfsburg', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (102, 51, 'Helmstedt – Wolfsburg', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (103, 52, 'Goslar – Northeim – Osterode', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (104, 52, 'Goslar – Northeim – Osterode', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (105, 53, 'Göttingen', NULL, 3, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (106, 53, 'Göttingen', NULL, 3, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (107, 54, 'Bremen I', NULL, 11, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (108, 54, 'Bremen I', NULL, 11, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (109, 55, 'Bremen II – Bremerhaven', NULL, 11, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (110, 55, 'Bremen II – Bremerhaven', NULL, 11, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (111, 56, 'Prignitz – Ostprignitz-Ruppin – Havelland I', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (112, 56, 'Prignitz – Ostprignitz-Ruppin – Havelland I', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (113, 57, 'Uckermark – Barnim I', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (114, 57, 'Uckermark – Barnim I', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (115, 58, 'Oberhavel – Havelland II', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (116, 58, 'Oberhavel – Havelland II', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (117, 59, 'Märkisch-Oderland – Barnim II', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (118, 59, 'Märkisch-Oderland – Barnim II', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (119, 60, 'Brandenburg an der Havel – Potsdam-Mittelmark I – Havelland III – Teltow-Fläming I', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (120, 60, 'Brandenburg an der Havel – Potsdam-Mittelmark I – Havelland III – Teltow-Fläming I', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (121, 61, 'Potsdam – Potsdam-Mittelmark II – Teltow-Fläming II', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (122, 61, 'Potsdam – Potsdam-Mittelmark II – Teltow-Fläming II', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (123, 62, 'Dahme-Spreewald – Teltow-Fläming III – Oberspreewald-Lausitz I', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (124, 62, 'Dahme-Spreewald – Teltow-Fläming III – Oberspreewald-Lausitz I', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (125, 63, 'Frankfurt (Oder) – Oder-Spree', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (126, 63, 'Frankfurt (Oder) – Oder-Spree', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (127, 64, 'Cottbus – Spree-Neiße', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (128, 64, 'Cottbus – Spree-Neiße', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (129, 65, 'Elbe-Elster – Oberspreewald-Lausitz II', NULL, 14, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (130, 65, 'Elbe-Elster – Oberspreewald-Lausitz II', NULL, 14, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (131, 66, 'Altmark', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (132, 66, 'Altmark', NULL, 6, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (133, 67, 'Börde – Jerichower Land', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (134, 67, 'Börde – Jerichower Land', NULL, 6, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (135, 68, 'Harz', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (136, 68, 'Harz', NULL, 6, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (137, 69, 'Magdeburg', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (138, 69, 'Magdeburg', NULL, 6, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (139, 70, 'Dessau – Wittenberg', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (140, 70, 'Dessau – Wittenberg', NULL, 6, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (141, 71, 'Anhalt', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (142, 71, 'Anhalt', NULL, 6, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (143, 72, 'Halle', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (144, 72, 'Halle', NULL, 6, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (145, 73, 'Burgenland – Saalekreis', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (146, 73, 'Burgenland – Saalekreis', NULL, 6, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (147, 74, 'Mansfeld', NULL, 6, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (148, 74, 'Mansfeld', NULL, 6, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (149, 75, 'Berlin-Mitte', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (150, 75, 'Berlin-Mitte', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (151, 76, 'Berlin-Pankow', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (152, 76, 'Berlin-Pankow', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (153, 77, 'Berlin-Reinickendorf', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (154, 77, 'Berlin-Reinickendorf', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (155, 78, 'Berlin-Spandau – Charlottenburg Nord', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (156, 78, 'Berlin-Spandau – Charlottenburg Nord', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (157, 79, 'Berlin-Steglitz-Zehlendorf', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (158, 79, 'Berlin-Steglitz-Zehlendorf', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (159, 80, 'Berlin-Charlottenburg-Wilmersdorf', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (160, 80, 'Berlin-Charlottenburg-Wilmersdorf', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (161, 81, 'Berlin-Tempelhof-Schöneberg', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (162, 81, 'Berlin-Tempelhof-Schöneberg', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (163, 82, 'Berlin-Neukölln', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (164, 82, 'Berlin-Neukölln', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (165, 83, 'Berlin-Friedrichshain-Kreuzberg – Prenzlauer Berg Ost', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (166, 83, 'Berlin-Friedrichshain-Kreuzberg – Prenzlauer Berg Ost', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (167, 84, 'Berlin-Treptow-Köpenick', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (168, 84, 'Berlin-Treptow-Köpenick', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (169, 85, 'Berlin-Marzahn-Hellersdorf', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (170, 85, 'Berlin-Marzahn-Hellersdorf', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (171, 86, 'Berlin-Lichtenberg', NULL, 1, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (172, 86, 'Berlin-Lichtenberg', NULL, 1, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (173, 87, 'Aachen I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (174, 87, 'Aachen I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (175, 88, 'Aachen II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (176, 88, 'Aachen II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (177, 89, 'Heinsberg', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (178, 89, 'Heinsberg', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (179, 90, 'Düren', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (180, 90, 'Düren', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (181, 91, 'Rhein-Erft-Kreis I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (182, 91, 'Rhein-Erft-Kreis I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (183, 92, 'Euskirchen – Rhein-Erft-Kreis II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (184, 92, 'Euskirchen – Rhein-Erft-Kreis II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (185, 93, 'Köln I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (186, 93, 'Köln I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (187, 94, 'Köln II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (188, 94, 'Köln II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (189, 95, 'Köln III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (190, 95, 'Köln III', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (191, 96, 'Bonn', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (192, 96, 'Bonn', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (193, 97, 'Rhein-Sieg-Kreis I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (194, 97, 'Rhein-Sieg-Kreis I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (195, 98, 'Rhein-Sieg-Kreis II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (196, 98, 'Rhein-Sieg-Kreis II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (197, 99, 'Oberbergischer Kreis', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (198, 99, 'Oberbergischer Kreis', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (199, 100, 'Rheinisch-Bergischer Kreis', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (200, 100, 'Rheinisch-Bergischer Kreis', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (201, 101, 'Leverkusen – Köln IV', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (202, 101, 'Leverkusen – Köln IV', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (203, 102, 'Wuppertal I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (204, 102, 'Wuppertal I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (205, 103, 'Solingen – Remscheid – Wuppertal II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (206, 103, 'Solingen – Remscheid – Wuppertal II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (207, 104, 'Mettmann I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (208, 104, 'Mettmann I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (209, 105, 'Mettmann II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (210, 105, 'Mettmann II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (211, 106, 'Düsseldorf I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (212, 106, 'Düsseldorf I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (213, 107, 'Düsseldorf II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (214, 107, 'Düsseldorf II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (215, 108, 'Neuss I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (216, 108, 'Neuss I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (217, 109, 'Mönchengladbach', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (218, 109, 'Mönchengladbach', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (219, 110, 'Krefeld I – Neuss II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (220, 110, 'Krefeld I – Neuss II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (221, 111, 'Viersen', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (222, 111, 'Viersen', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (223, 112, 'Kleve', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (224, 112, 'Kleve', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (225, 113, 'Wesel I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (226, 113, 'Wesel I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (227, 114, 'Krefeld II – Wesel II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (228, 114, 'Krefeld II – Wesel II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (229, 115, 'Duisburg I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (230, 115, 'Duisburg I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (231, 116, 'Duisburg II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (232, 116, 'Duisburg II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (233, 117, 'Oberhausen – Wesel III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (234, 117, 'Oberhausen – Wesel III', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (235, 118, 'Mülheim – Essen I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (236, 118, 'Mülheim – Essen I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (237, 119, 'Essen II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (238, 119, 'Essen II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (239, 120, 'Essen III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (240, 120, 'Essen III', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (241, 121, 'Recklinghausen I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (242, 121, 'Recklinghausen I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (243, 122, 'Recklinghausen II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (244, 122, 'Recklinghausen II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (245, 123, 'Gelsenkirchen', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (246, 123, 'Gelsenkirchen', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (247, 124, 'Steinfurt I – Borken I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (248, 124, 'Steinfurt I – Borken I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (249, 125, 'Bottrop – Recklinghausen III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (250, 125, 'Bottrop – Recklinghausen III', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (251, 126, 'Borken II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (252, 126, 'Borken II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (253, 127, 'Coesfeld – Steinfurt II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (254, 127, 'Coesfeld – Steinfurt II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (255, 128, 'Steinfurt III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (256, 128, 'Steinfurt III', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (257, 129, 'Münster', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (258, 129, 'Münster', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (259, 130, 'Warendorf', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (260, 130, 'Warendorf', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (261, 131, 'Gütersloh I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (262, 131, 'Gütersloh I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (263, 132, 'Bielefeld – Gütersloh II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (264, 132, 'Bielefeld – Gütersloh II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (265, 133, 'Herford – Minden-Lübbecke II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (266, 133, 'Herford – Minden-Lübbecke II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (267, 134, 'Minden-Lübbecke I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (268, 134, 'Minden-Lübbecke I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (269, 135, 'Lippe I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (270, 135, 'Lippe I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (271, 136, 'Höxter – Lippe II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (272, 136, 'Höxter – Lippe II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (273, 137, 'Paderborn – Gütersloh III', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (274, 137, 'Paderborn – Gütersloh III', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (275, 138, 'Hagen – Ennepe-Ruhr-Kreis I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (276, 138, 'Hagen – Ennepe-Ruhr-Kreis I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (277, 139, 'Ennepe-Ruhr-Kreis II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (278, 139, 'Ennepe-Ruhr-Kreis II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (279, 140, 'Bochum I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (280, 140, 'Bochum I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (281, 141, 'Herne – Bochum II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (282, 141, 'Herne – Bochum II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (283, 142, 'Dortmund I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (284, 142, 'Dortmund I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (285, 143, 'Dortmund II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (286, 143, 'Dortmund II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (287, 144, 'Unna I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (288, 144, 'Unna I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (289, 145, 'Hamm – Unna II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (290, 145, 'Hamm – Unna II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (291, 146, 'Soest', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (292, 146, 'Soest', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (293, 147, 'Hochsauerlandkreis', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (294, 147, 'Hochsauerlandkreis', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (295, 148, 'Siegen-Wittgenstein', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (296, 148, 'Siegen-Wittgenstein', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (297, 149, 'Olpe – Märkischer Kreis I', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (298, 149, 'Olpe – Märkischer Kreis I', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (299, 150, 'Märkischer Kreis II', NULL, 5, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (300, 150, 'Märkischer Kreis II', NULL, 5, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (301, 151, 'Nordsachsen', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (302, 151, 'Nordsachsen', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (303, 152, 'Leipzig I', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (304, 152, 'Leipzig I', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (305, 153, 'Leipzig II', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (306, 153, 'Leipzig II', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (307, 154, 'Leipzig-Land', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (308, 154, 'Leipzig-Land', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (309, 155, 'Meißen', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (310, 155, 'Meißen', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (311, 156, 'Bautzen I', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (312, 156, 'Bautzen I', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (313, 157, 'Görlitz', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (314, 157, 'Görlitz', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (315, 158, 'Sächsische Schweiz-Osterzgebirge', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (316, 158, 'Sächsische Schweiz-Osterzgebirge', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (317, 159, 'Dresden I', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (318, 159, 'Dresden I', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (319, 160, 'Dresden II – Bautzen II', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (320, 160, 'Dresden II – Bautzen II', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (321, 161, 'Mittelsachsen', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (322, 161, 'Mittelsachsen', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (323, 162, 'Chemnitz', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (324, 162, 'Chemnitz', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (325, 163, 'Chemnitzer Umland – Erzgebirgskreis II', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (326, 163, 'Chemnitzer Umland – Erzgebirgskreis II', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (327, 164, 'Erzgebirgskreis I', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (328, 164, 'Erzgebirgskreis I', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (329, 165, 'Zwickau', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (330, 165, 'Zwickau', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (331, 166, 'Vogtlandkreis', NULL, 16, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (332, 166, 'Vogtlandkreis', NULL, 16, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (333, 167, 'Waldeck', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (334, 167, 'Waldeck', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (335, 168, 'Kassel', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (336, 168, 'Kassel', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (337, 169, 'Werra-Meißner – Hersfeld-Rotenburg', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (338, 169, 'Werra-Meißner – Hersfeld-Rotenburg', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (339, 170, 'Schwalm-Eder', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (340, 170, 'Schwalm-Eder', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (341, 171, 'Marburg', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (342, 171, 'Marburg', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (343, 172, 'Lahn-Dill', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (344, 172, 'Lahn-Dill', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (345, 173, 'Gießen', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (346, 173, 'Gießen', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (347, 174, 'Fulda', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (348, 174, 'Fulda', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (349, 175, 'Main-Kinzig – Wetterau II – Schotten', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (350, 175, 'Main-Kinzig – Wetterau II – Schotten', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (351, 176, 'Hochtaunus', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (352, 176, 'Hochtaunus', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (353, 177, 'Wetterau I', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (354, 177, 'Wetterau I', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (355, 178, 'Rheingau-Taunus – Limburg', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (356, 178, 'Rheingau-Taunus – Limburg', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (357, 179, 'Wiesbaden', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (358, 179, 'Wiesbaden', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (359, 180, 'Hanau', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (360, 180, 'Hanau', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (361, 181, 'Main-Taunus', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (362, 181, 'Main-Taunus', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (363, 182, 'Frankfurt am Main I', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (364, 182, 'Frankfurt am Main I', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (365, 183, 'Frankfurt am Main II', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (366, 183, 'Frankfurt am Main II', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (367, 184, 'Groß-Gerau', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (368, 184, 'Groß-Gerau', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (369, 185, 'Offenbach', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (370, 185, 'Offenbach', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (371, 186, 'Darmstadt', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (372, 186, 'Darmstadt', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (373, 187, 'Odenwald', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (374, 187, 'Odenwald', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (375, 188, 'Bergstraße', NULL, 7, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (376, 188, 'Bergstraße', NULL, 7, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (377, 189, 'Eichsfeld – Nordhausen – Unstrut-Hainich-Kreis I', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (378, 189, 'Eichsfeld – Nordhausen – Unstrut-Hainich-Kreis I', NULL, 9, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (379, 190, 'Eisenach – Wartburgkreis – Unstrut-Hainich-Kreis II', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (380, 190, 'Eisenach – Wartburgkreis – Unstrut-Hainich-Kreis II', NULL, 9, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (381, 191, 'Kyffhäuserkreis – Sömmerda – Weimarer Land I', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (382, 191, 'Kyffhäuserkreis – Sömmerda – Weimarer Land I', NULL, 9, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (383, 192, 'Gotha – Ilm-Kreis', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (384, 192, 'Gotha – Ilm-Kreis', NULL, 9, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (385, 193, 'Erfurt – Weimar – Weimarer Land II', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (386, 193, 'Erfurt – Weimar – Weimarer Land II', NULL, 9, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (387, 194, 'Gera – Jena – Saale-Holzland-Kreis', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (388, 194, 'Gera – Jena – Saale-Holzland-Kreis', NULL, 9, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (389, 195, 'Greiz – Altenburger Land', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (390, 195, 'Greiz – Altenburger Land', NULL, 9, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (391, 196, 'Sonneberg – Saalfeld-Rudolstadt – Saale-Orla-Kreis', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (392, 196, 'Sonneberg – Saalfeld-Rudolstadt – Saale-Orla-Kreis', NULL, 9, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (393, 197, 'Suhl – Schmalkalden-Meiningen – Hildburghausen', NULL, 9, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (394, 197, 'Suhl – Schmalkalden-Meiningen – Hildburghausen', NULL, 9, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (395, 198, 'Neuwied', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (396, 198, 'Neuwied', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (397, 199, 'Ahrweiler', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (398, 199, 'Ahrweiler', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (399, 200, 'Koblenz', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (400, 200, 'Koblenz', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (401, 201, 'Mosel/Rhein-Hunsrück', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (402, 201, 'Mosel/Rhein-Hunsrück', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (403, 202, 'Kreuznach', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (404, 202, 'Kreuznach', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (405, 203, 'Bitburg', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (406, 203, 'Bitburg', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (407, 204, 'Trier', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (408, 204, 'Trier', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (409, 205, 'Montabaur', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (410, 205, 'Montabaur', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (411, 206, 'Mainz', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (412, 206, 'Mainz', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (413, 207, 'Worms', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (414, 207, 'Worms', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (415, 208, 'Ludwigshafen/Frankenthal', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (416, 208, 'Ludwigshafen/Frankenthal', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (417, 209, 'Neustadt – Speyer', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (418, 209, 'Neustadt – Speyer', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (419, 210, 'Kaiserslautern', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (420, 210, 'Kaiserslautern', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (421, 211, 'Pirmasens', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (422, 211, 'Pirmasens', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (423, 212, 'Südpfalz', NULL, 2, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (424, 212, 'Südpfalz', NULL, 2, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (425, 213, 'Altötting', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (426, 213, 'Altötting', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (427, 214, 'Erding – Ebersberg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (428, 214, 'Erding – Ebersberg', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (429, 215, 'Freising', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (430, 215, 'Freising', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (431, 216, 'Fürstenfeldbruck', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (432, 216, 'Fürstenfeldbruck', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (433, 217, 'Ingolstadt', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (434, 217, 'Ingolstadt', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (435, 218, 'München-Nord', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (436, 218, 'München-Nord', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (437, 219, 'München-Ost', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (438, 219, 'München-Ost', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (439, 220, 'München-Süd', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (440, 220, 'München-Süd', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (441, 221, 'München-West/Mitte', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (442, 221, 'München-West/Mitte', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (443, 222, 'München-Land', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (444, 222, 'München-Land', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (445, 223, 'Rosenheim', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (446, 223, 'Rosenheim', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (447, 224, 'Starnberg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (448, 224, 'Starnberg', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (449, 225, 'Traunstein', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (450, 225, 'Traunstein', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (451, 226, 'Weilheim', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (452, 226, 'Weilheim', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (453, 227, 'Deggendorf', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (454, 227, 'Deggendorf', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (455, 228, 'Landshut', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (456, 228, 'Landshut', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (457, 229, 'Passau', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (458, 229, 'Passau', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (459, 230, 'Rottal-Inn', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (460, 230, 'Rottal-Inn', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (461, 231, 'Straubing', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (462, 231, 'Straubing', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (463, 232, 'Amberg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (464, 232, 'Amberg', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (465, 233, 'Regensburg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (466, 233, 'Regensburg', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (467, 234, 'Schwandorf', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (468, 234, 'Schwandorf', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (469, 235, 'Weiden', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (470, 235, 'Weiden', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (471, 236, 'Bamberg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (472, 236, 'Bamberg', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (473, 237, 'Bayreuth', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (474, 237, 'Bayreuth', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (475, 238, 'Coburg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (476, 238, 'Coburg', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (477, 239, 'Hof', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (478, 239, 'Hof', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (479, 240, 'Kulmbach', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (480, 240, 'Kulmbach', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (481, 241, 'Ansbach', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (482, 241, 'Ansbach', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (483, 242, 'Erlangen', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (484, 242, 'Erlangen', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (485, 243, 'Fürth', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (486, 243, 'Fürth', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (487, 244, 'Nürnberg-Nord', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (488, 244, 'Nürnberg-Nord', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (489, 245, 'Nürnberg-Süd', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (490, 245, 'Nürnberg-Süd', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (491, 246, 'Roth', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (492, 246, 'Roth', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (493, 247, 'Aschaffenburg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (494, 247, 'Aschaffenburg', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (495, 248, 'Bad Kissingen', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (496, 248, 'Bad Kissingen', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (497, 249, 'Main-Spessart', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (498, 249, 'Main-Spessart', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (499, 250, 'Schweinfurt', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (500, 250, 'Schweinfurt', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (501, 251, 'Würzburg', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (502, 251, 'Würzburg', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (503, 252, 'Augsburg-Stadt', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (504, 252, 'Augsburg-Stadt', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (505, 253, 'Augsburg-Land', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (506, 253, 'Augsburg-Land', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (507, 254, 'Donau-Ries', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (508, 254, 'Donau-Ries', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (509, 255, 'Neu-Ulm', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (510, 255, 'Neu-Ulm', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (511, 256, 'Oberallgäu', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (512, 256, 'Oberallgäu', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (513, 257, 'Ostallgäu', NULL, 4, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (514, 257, 'Ostallgäu', NULL, 4, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (515, 258, 'Stuttgart I', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (516, 258, 'Stuttgart I', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (517, 259, 'Stuttgart II', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (518, 259, 'Stuttgart II', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (519, 260, 'Böblingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (520, 260, 'Böblingen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (521, 261, 'Esslingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (522, 261, 'Esslingen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (523, 262, 'Nürtingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (524, 262, 'Nürtingen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (525, 263, 'Göppingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (526, 263, 'Göppingen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (527, 264, 'Waiblingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (528, 264, 'Waiblingen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (529, 265, 'Ludwigsburg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (530, 265, 'Ludwigsburg', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (531, 266, 'Neckar-Zaber', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (532, 266, 'Neckar-Zaber', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (533, 267, 'Heilbronn', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (534, 267, 'Heilbronn', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (535, 268, 'Schwäbisch Hall – Hohenlohe', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (536, 268, 'Schwäbisch Hall – Hohenlohe', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (537, 269, 'Backnang – Schwäbisch Gmünd', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (538, 269, 'Backnang – Schwäbisch Gmünd', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (539, 270, 'Aalen – Heidenheim', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (540, 270, 'Aalen – Heidenheim', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (541, 271, 'Karlsruhe-Stadt', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (542, 271, 'Karlsruhe-Stadt', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (543, 272, 'Karlsruhe-Land', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (544, 272, 'Karlsruhe-Land', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (545, 273, 'Rastatt', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (546, 273, 'Rastatt', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (547, 274, 'Heidelberg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (548, 274, 'Heidelberg', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (549, 275, 'Mannheim', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (550, 275, 'Mannheim', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (551, 276, 'Odenwald – Tauber', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (552, 276, 'Odenwald – Tauber', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (553, 277, 'Rhein-Neckar', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (554, 277, 'Rhein-Neckar', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (555, 278, 'Bruchsal – Schwetzingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (556, 278, 'Bruchsal – Schwetzingen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (557, 279, 'Pforzheim', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (558, 279, 'Pforzheim', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (559, 280, 'Calw', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (560, 280, 'Calw', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (561, 281, 'Freiburg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (562, 281, 'Freiburg', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (563, 282, 'Lörrach – Müllheim', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (564, 282, 'Lörrach – Müllheim', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (565, 283, 'Emmendingen – Lahr', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (566, 283, 'Emmendingen – Lahr', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (567, 284, 'Offenburg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (568, 284, 'Offenburg', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (569, 285, 'Rottweil – Tuttlingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (570, 285, 'Rottweil – Tuttlingen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (571, 286, 'Schwarzwald-Baar', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (572, 286, 'Schwarzwald-Baar', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (573, 287, 'Konstanz', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (574, 287, 'Konstanz', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (575, 288, 'Waldshut', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (576, 288, 'Waldshut', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (577, 289, 'Reutlingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (578, 289, 'Reutlingen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (579, 290, 'Tübingen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (580, 290, 'Tübingen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (581, 291, 'Ulm', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (582, 291, 'Ulm', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (583, 292, 'Biberach', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (584, 292, 'Biberach', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (585, 293, 'Bodensee', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (586, 293, 'Bodensee', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (587, 294, 'Ravensburg', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (588, 294, 'Ravensburg', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (589, 295, 'Zollernalb – Sigmaringen', NULL, 10, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (590, 295, 'Zollernalb – Sigmaringen', NULL, 10, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (591, 296, 'Saarbrücken', NULL, 12, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (592, 296, 'Saarbrücken', NULL, 12, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (593, 297, 'Saarlouis', NULL, 12, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (594, 297, 'Saarlouis', NULL, 12, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (595, 298, 'St. Wendel', NULL, 12, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (596, 298, 'St. Wendel', NULL, 12, 2013);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (597, 299, 'Homburg', NULL, 12, 2009);
insert into Wahlkreis (wkid, wknr, name, outline, fsid, year) VALUES (598, 299, 'Homburg', NULL, 12, 2013);
