#!/bin/bash
psql -d wisdb -c "CREATE USER uiuser WITH PASSWORD 'uiuser123';"
psql -d wisdb -c "GRANT CONNECT ON DATABASE WisDB TO uiuser;"
psql -d wisdb -c "GRANT USAGE ON SCHEMA public TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_Seatdistribution_Bundestag TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_Delegates TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_WahlkreisOverview_FirstVoteWinners TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_WahlkreisOverview_SecondVoteDistribution TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_Results_View_WahlkreisOverview_Voterparticipation TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_WahlkreisOverview_FirstVoteWinners_SLOW TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_WahlkreisOverview_SecondVoteDistribution_SLOW TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_Wahlkreiswinners TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_UeberhangsMandate TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Results_View_NarrowWahlkreisWinsAndLosings TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON WahlscheinEntries TO uiuser;"
psql -d wisdb -c "GRANT EXECUTE ON FUNCTION random_string(INTEGER) TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON CitizenRegistration TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Citizen TO uiuser;"
psql -d wisdb -c "GRANT Select ON hasvoted TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON ElectionYear TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Wahlkreis TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON FederalState TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON tokens TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Votables TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON Wahlbezirk TO uiuser;"
psql -d wisdb -c "GRANT SELECT ON DirektwahlbezirkData TO uiuser;"
psql -d wisdb -c "GRANT UPDATE ON hasvoted TO uiuser;"
psql -d wisdb -c "GRANT INSERT ON stimmzettel TO uiuser;"
psql -d wisdb -c "GRANT INSERT ON tokens TO uiuser;"
